- azure-pipelines.yml
- package.json
- web/e2e/BUILD.bazel
- web/e2e/protractor.on-prepare.js
- web/e2e/src/app.e2e-spec.ts
- web/e2e/src/app.po.ts
- web/e2e/tsconfig.json
- web/src/BUILD.bazel
- web/src/yngdieng/utils.spec.ts
also added yngdieng/util.spec.ts
> chore(web): set up e2e tests

- web/src/app/sidenav-content/sidenav-content.component.html
- web/src/app/sidenav-content/sidenav-content.component.ts
> feat(web): 反馈链接

- web/src/static/index.html
- web/src/static/index.prod.html
在 index.html 和 index.prod.html 两个文件里都加了那段代码。
> added google analytics script

- docker-compose.yaml
- docker/yngdieng-backend/Dockerfile
- server/backend/HealthChecks/IndexHealthCheck.cs
- server/backend/IndexHolder.cs
- server/backend/IndexLoaderBackgroundService.cs
- server/backend/Startup.cs
- web/src/environments/environment.dev.ts
Also, move index loading to a background service (instead on the first request).
#130
> Create health check

- web/src/yngdieng/explanations.ts
> feat(ui): add period

- web/src/app/mono-hanzi-result/mono-hanzi-result.component.html
> fixed a type in detail page

- server/indexer/Loading/FengLoader.cs
- server/protos/shared/documents.proto
- shared/documents.proto
> feat(indexer): 冯单字音

- .azure/pipelines/docker-images.yml
- assets/.gitignore
- assets/BUILD
- assets/ffmpeg.bzl
- docker/yngdieng-backend/Dockerfile
- server/backend/Controllers/TtsController.cs
- server/backend/Startup.cs
> feat(backend): REST endpoint for getting TTS Audio output

- web/src/app/app.module.ts
- web/src/app/audio-player/audio-player.component.html
- web/src/app/audio-player/audio-player.component.spec.ts
- web/src/app/audio-player/audio-player.component.ts
- web/src/app/details-feng/details-feng.component.html
- web/src/app/details-feng/details-feng.component.ts
> feat(ui): basic TTS UI

- server/indexer/.vscode/launch.json
- server/indexer/.vscode/tasks.json
- server/indexer/Processing/YngdiengDocumentUtil.cs
- server/indexer/Yngdieng.Indexer.csproj
- server/protos/Yngdieng.Protos.csproj
> feat(indexer): populate more fields in the combined YngdiengDocument

- miniapp/src/app.tsx
测试过。 iOS，Android 最新版本的微信都可以播放。静音也可以播放。
不知道需不需要考虑SDK向后兼容的问题。
> ignore system mute on ios

- server/common/YngpingVariantsUtil.cs
- server/indexer/IndexV1Creator.cs
- server/indexer/IndexV2Creator.cs
- server/indexer/Loading/FengLoader.cs
- server/indexer/OpenCcClient.cs
feat(indexer): index tweaking #627
支持更多榕拼模糊音。字头支持简体(hacky)。
Issues: #261 #333
> feat(indexer): index tweaking

- web/src/app/richtext-flatten.pipe.ts
- web/src/app/word-card/word-card.component.html
- web/src/app/word-card/word-card.component.ts
feat(web): add audio player button to search v2 results #628
> feat(web): add audio player button to search v2 results

- miniapp/src/app.tsx
- miniapp/src/pages/collectionDetail/collectionDetail.tsx
- miniapp/src/pages/index/index.tsx
- miniapp/src/pages/wordDetail/wordDetail.tsx
- miniapp/src/store/actions/collection.ts
支持公众号文张卡片跳转到小程序时的参数解析，顺便修了一些小问题。
扫描二维码的参数解析部分现在还不能测试，等配置完成并测试没问题了再进行合并。
> feat(miniapp): parsing url

- docker/yngdieng-backend/Dockerfile
- package.json
- run_backend.sh
- server/backend/Controllers/TtsController.cs
- server/backend/Program.cs
- server/backend/TextToSpeech/AudioConversion.cs
- server/backend/Yngdieng.Backend.csproj
- web/src/BUILD.bazel
- web/src/app/BUILD
- web/src/app/app.module.ts
- web/src/app/audio-player/audio-player.component.ts
- web/src/app/word-details-hero/word-details-hero.component.html
- web/src/app/word-details/word-details.component.ts
- web/src/material/material.module.ts
- yarn.lock
> fix(web): fix audio playback on iOS / Safari

- miniapp/src/pages/collectionDetail/collectionDetail.config.ts
- miniapp/src/pages/collectionDetail/collectionDetail.tsx
- miniapp/src/pages/index/index.config.ts
- miniapp/src/pages/index/index.tsx
- miniapp/src/pages/search/search.config.ts
- miniapp/src/pages/search/search.tsx
- miniapp/src/pages/wordDetail/wordDetail.config.ts
- miniapp/src/pages/wordDetail/wordDetail.tsx
> feat(miniapp): miniapp share

- .azure/pipelines/docker-images.yml
- server/Yngdieng.Search.Common/LuceneUtils.cs
- server/backend/Services/YngdiengService.SearchV2.cs
- server/indexer/IndexV2Creator.cs
- server/protos/shared/services.proto
- shared/BUILD
- shared/services.proto
- web/src/BUILD.bazel
- web/src/app/BUILD
- web/src/app/app-routing.module.ts
- web/src/app/app.module.ts
- web/src/app/local-storage.service.ts
- web/src/app/settings/settings.component.html
- web/src/app/settings/settings.component.spec.ts
- web/src/app/settings/settings.component.ts
- web/src/app/sidenav-content/sidenav-content.component.html
- web/src/app/sidenav-content/sidenav-content.component.ts
- web/src/app/user-settings.service.ts
- web/src/app/yngdieng-backend.service.ts
- web/src/environments/environment.dev.ts
- web/src/environments/environment.prod.ts
- web/src/environments/environment.staging.ts
- web/src/environments/environment.ts
- web/src/material/material.module.ts
- web/src/protos/BUILD
- web/src/protos/settings.proto
* settings page
* local storage
* send UserPreference as request header
> Filter sourceless entries

- web/src/app/audio-ack-dialog/audio-ack-dialog.component.scss
- web/src/app/audio-player/audio-player.component.ts
- web/src/app/debug-info/debug-info.component.ts
- web/src/environments/environment.dev.ts
- In audio player, use `local-storage.service.ts` for local storage access;
- Updated dialog stylesheet
> tts acknowledgment dialog update

- server/backend/Db/Queries.cs
- server/backend/Services/Frontend/AudioResources.cs
- server/backend/Services/Frontend/Renderers.cs
- server/backend/Services/Frontend/Words.cs
- server/backend/Services/PhonologyUtils.cs
> frontend v3 fixes

- docker/yngdieng-backend/Dockerfile
- server/backend/HealthChecks/TtsHealthCheck.cs
- server/backend/Services/Frontend/AudioResources.cs
- server/backend/Startup.cs
- server/backend/TextToSpeech/YngpingAudioSynthesizer.cs
- server/backend/TextToSpeech/YngpingTtsUtil.cs
- server/backend/Yngdieng.Backend.csproj
- server/common/Yngdieng.Common.csproj
- server/indexer/Yngdieng.Indexer.csproj
- servertests/backend/TextToSpeech/YngpingTtsUtilTest.cs
> feat(tts): better fallback, and hide audio button where unpronounceable

- miniapp/package.json
- miniapp/src/pages/search/search.tsx
> fix(miniapp): 防止分享编码

- miniapp/src/components/selectableText/selectable-text.js
- miniapp/src/components/selectableText/selectable-text.json
- miniapp/src/components/selectableText/selectable-text.wxml
- miniapp/src/pages/wordDetail/wordDetail.config.ts
- miniapp/src/pages/wordDetail/wordDetail.module.scss
- miniapp/src/pages/wordDetail/wordDetail.tsx
> feat(miniapp): wordDetail 允许选中文本

- server/backend/Services/YngdiengService.GenerateSandhi.cs
- server/backend/Yngdieng.Backend.csproj
- server/protos/shared/services.proto
- shared/services.proto
- web/src/app/app-routing.module.ts
- web/src/app/app.component.ts
- web/src/app/app.module.ts
- web/src/app/sandhi-tool/sandhi-tool.component.html
- web/src/app/sandhi-tool/sandhi-tool.component.scss
- web/src/app/sandhi-tool/sandhi-tool.component.ts
- web/src/app/yngdieng-backend.service.ts
> feat: 连读计算器

- miniapp/project.config.json
- miniapp/src/pages/wordDetail/wordDetail.module.scss
- miniapp/src/pages/wordDetail/wordDetail.tsx
> feat(miniapp): label for Hanzi

- web/src/lib/utils.ts
> fix(web): Update utils.ts  非 -> 喜

- miniapp/src/pages/index/index.tsx
https://miniapp.ydict.net/campaign/foochowka-3
> feat(miniapp): 增加福州客词表的重定向

- miniapp/config/index.js
- miniapp/src/app.config.ts
- miniapp/src/pages/collectionDetail/collectionDetail.config.ts
- miniapp/src/pages/collectionDetail/collectionDetail.tsx
- miniapp/src/pages/index/index.config.ts
- miniapp/src/pages/index/index.tsx
- miniapp/src/pages/search/search.config.ts
- miniapp/src/pages/search/search.tsx
- miniapp/src/pages/wordDetail/wordDetail.config.ts
- miniapp/src/pages/wordDetail/wordDetail.tsx
- miniapp/src/sitemap.json
- miniapp/src/utils/sharing-util.ts
> feat(miniapp): 新增分享到朋友圈
